# Generated by Django 3.2 on 2025-05-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblUser',
            new_name='tbl_user',
        ),
    ]
