# Generated by Django 3.2 on 2025-05-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_tbluser_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='visa_inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('desired_country', models.CharField(choices=[('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('USA', 'USA'), ('UK', 'UK'), ('Europe', 'Europe'), ('Any Other', 'Any Other')], max_length=50)),
                ('desired_visa_service', models.CharField(choices=[('Permanent Residency', 'Permanent Residency'), ('Work Permit', 'Work Permit'), ('State Nomination', 'State Nomination'), ('Investment', 'Investment'), ('Business', 'Business'), ('Visitor Visa', 'Visitor Visa'), ('PR - RNIP', 'PR - RNIP'), ('PR - AIPP', 'PR - AIPP'), ('Blood Relation', 'Blood Relation'), ('Student Visa', 'Student Visa')], max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('interested_in_coaching', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('TOEFL IBT', 'TOEFL IBT'), ('GRE', 'GRE'), ('PTE', 'PTE'), ('SAT', 'SAT'), ('Other', 'Other')], max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('captcha_entered', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visa_inquiry',
            },
        ),
    ]
