# Generated by Django 3.2 on 2025-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tbl_country_tbl_courses_tbl_visa_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='img_gallary/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_gallary',
            },
        ),
        migrations.RemoveField(
            model_name='tbl_courses',
            name='course',
        ),
        migrations.AddField(
            model_name='tbl_country',
            name='about',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_courses',
            name='course_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_courses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_visa_service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_visa_service',
            name='image',
            field=models.ImageField(null=True, upload_to='img_visa/'),
        ),
        migrations.AlterField(
            model_name='tbl_country',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_visa_service',
            name='visa_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
