# Generated by Django 3.2 on 2025-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250507_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_gallary',
            old_name='about',
            new_name='drive_url',
        ),
        migrations.AlterField(
            model_name='tbl_gallary',
            name='image',
            field=models.ImageField(null=True, upload_to='img_gallary/'),
        ),
    ]
