# Generated by Django 3.2 on 2025-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250507_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(blank=True, max_length=50, null=True)),
                ('video_drive_url', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_video',
            },
        ),
        migrations.AddField(
            model_name='tbl_gallary',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_gallary',
            name='image',
            field=models.ImageField(default='others/default/default.jpeg', null=True, upload_to='img_gallary/'),
        ),
        migrations.AlterField(
            model_name='tbl_visa_service',
            name='image',
            field=models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_visa/'),
        ),
    ]
