# Generated by Django 3.2 on 2025-05-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250508_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_courses',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
