# Generated by Django 3.2 on 2025-05-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tbl_courses_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_courses',
            name='image',
            field=models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_course/'),
        ),
    ]
