# Generated by Django 3.2 on 2025-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tbl_courses_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_success_stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_visa/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_success_stories',
            },
        ),
    ]
