# Generated by Django 3.2 on 2025-05-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tbl_success_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_blogs/')),
                ('description', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_blog',
            },
        ),
        migrations.CreateModel(
            name='tbl_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('desired_visa_service', models.CharField(choices=[('Permanent Residency', 'Permanent Residency'), ('Work Permit', 'Work Permit'), ('State Nomination', 'State Nomination'), ('Investment', 'Investment'), ('Business', 'Business'), ('Visitor Visa', 'Visitor Visa'), ('PR - RNIP', 'PR - RNIP'), ('PR - AIPP', 'PR - AIPP'), ('Blood Relation', 'Blood Relation'), ('Student Visa', 'Student Visa')], max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('captcha_entered', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_cv',
            },
        ),
    ]
