# Generated by Django 3.2 on 2025-05-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_tbl_home_tbl_news_tbl_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallary',
        ),
    ]
