# Generated by Django 3.2 on 2025-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_tbl_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_url', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='others/default/default.jpeg', null=True, upload_to='img_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_gallery',
            },
        ),
    ]
