# Generated by Django 3.2 on 2025-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_tbl_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_home',
            name='serial',
            field=models.IntegerField(default=1),
        ),
    ]
