# Generated by Django 3.2 on 2025-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_tbl_home_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_team',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_team',
            name='linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_team',
            name='tweeter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
