# Generated by Django 3.2 on 2025-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20250508_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_blog_comment',
            },
        ),
        migrations.AddField(
            model_name='tbl_blog',
            name='image2',
            field=models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_blogs/'),
        ),
        migrations.AddField(
            model_name='tbl_blog',
            name='image3',
            field=models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_blogs/'),
        ),
        migrations.AddField(
            model_name='tbl_blog',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_blog',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_blog',
            name='title3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_blog',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
