# Generated by Django 3.2 on 2025-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20250508_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
