# Generated by Django 3.2 on 2025-05-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_tbl_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=1)),
                ('heading', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='other/default/default.jpeg', null=True, upload_to='img_visa/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_about_us',
            },
        ),
    ]
