# Generated by Django 3.2 on 2025-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_tbl_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cv',
            name='desired_visa_service',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_inquiry_association',
            name='present_occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visa_inquiry',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visa_inquiry',
            name='desired_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visa_inquiry',
            name='desired_visa_service',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
