# Generated by Django 3.2 on 2025-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20250509_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_visa_service',
            name='image',
        ),
        migrations.AddField(
            model_name='tbl_gallery',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_visa_service',
            name='image_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
