# Generated by Django 3.2 on 2025-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20250509_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_visa_service',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
