# Generated by Django 3.2 on 2025-05-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20250510_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_home',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
