# Generated by Django 3.2 on 2025-05-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_tbl_home_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_success_stories',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
