# Generated by Django 3.2 on 2025-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_tbl_success_stories_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_about_founder',
        ),
        migrations.DeleteModel(
            name='tbl_about_race',
        ),
        migrations.AddField(
            model_name='tbl_about_us',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
