# Generated by Django 5.2.1 on 2025-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20250510_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_video',
            name='video_drive_url',
        ),
        migrations.AddField(
            model_name='tbl_video',
            name='row_video_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_video',
            name='video_embed_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
