# Generated by Django 5.2.1 on 2025-05-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_tbl_video_video_drive_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_education_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('stream_of_degree', models.CharField(max_length=100)),
                ('major_degree', models.CharField(max_length=100)),
                ('year_of_completion', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('total_backlog', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_education_qualification',
            },
        ),
        migrations.CreateModel(
            name='tbl_employeement_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('from_date', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=100)),
                ('no_of_years', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_employeement_detail',
            },
        ),
        migrations.CreateModel(
            name='tbl_exam_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(max_length=100)),
                ('exam', models.CharField(max_length=100)),
                ('listening', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=100)),
                ('writing', models.CharField(max_length=100)),
                ('speaking', models.CharField(max_length=100)),
                ('final_score', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exam_detail',
            },
        ),
        migrations.CreateModel(
            name='tbl_pr_visa_inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_country', models.CharField(max_length=50)),
                ('desired_visa_route', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('landline', models.CharField(max_length=50)),
                ('alt_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('marital_status', models.CharField(max_length=50)),
                ('no_of_child', models.CharField(max_length=50)),
                ('flat_no', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('road_street', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('inquiry_id', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_pr_visa_inquiry',
            },
        ),
        migrations.CreateModel(
            name='tbl_student_visa_inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Spouse', 'Spouse')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('landline_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('desired_country', models.CharField(max_length=50)),
                ('present_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_student_visa_inquiry',
            },
        ),
        migrations.CreateModel(
            name='tbl_test_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(max_length=100)),
                ('exam', models.CharField(max_length=100)),
                ('verbal_reasoning', models.CharField(max_length=100)),
                ('quantitative_reasoning', models.CharField(max_length=100)),
                ('analytical_writing', models.CharField(max_length=100)),
                ('final_score', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_test_detail',
            },
        ),
    ]
