# Generated by Django 5.2.1 on 2025-06-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_personalizedguidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_study_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('study_faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('college_nature', models.CharField(blank=True, max_length=100, null=True)),
                ('study_level', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('add_date', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_count', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_study_course',
            },
        ),
        migrations.CreateModel(
            name='tbl_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('position_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancy_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancy_count', models.CharField(blank=True, max_length=100, null=True)),
                ('master_agent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_vacancy',
            },
        ),
    ]
