# Generated by Django 5.2.1 on 2025-06-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_tbl_course_name_tbl_industry_type_tbl_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_inquiry_association',
            name='form_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
